### ISSUE TITLE
Editar en CRUD de Riesgos

### ISSUE THREAD

**Issue by MGeovany** [MGeovany/matriz-analisis-de-riesgos#4]
Modal de editar no esta trayendo la informacion completa, todos los campos funciona excepto, `descripcion` & `tiempo` la informacion no la esta almacenando.

![image](https://user-images.githubusercontent.com/37640685/185240572-23786d6b-00fc-444e-b650-e7270d5d6bed.png)

**Comment by chavarriaa** [comment]
Solucionado. Tiempo no lo guardaremos al final
